import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "AI Content Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.className} antialiased bg-slate-100`}>
          <NextTopLoader />
          <main>{children}</main>
          <Toaster
            expand
            position={"bottom-left"}
            visibleToasts={2}
            theme={"light"}
            toastOptions={{ duration: 2000 }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
